### ISSUE TITLE
"Not Synchronizing - 0%"

### ISSUE THREAD

**Issue by rachelaux** [zkopru-network/wallet#20]
This language makes it sounds bad that it is not synchronizing. When a user logs in and see this does it mean "all good" or "there's an issue cuz it's not synching". If I'm correct that it means the former, Maybe we should say, "Synchronized"

<img width="1662" alt="Screen Shot 2021-11-14 at 1 41 28 PM" src="https://user-images.githubusercontent.com/81319667/141695961-6abfa541-d74c-40dd-93cc-e228a955b4f8.png">

**Comment by JChanceHud** [comment]
Yea, this happens when the node is initializing. "Synchronized" may not technically be correct, something like "Initializing" might be better.
