### ISSUE TITLE
Standard and Fast buttons populate the same results

### ISSUE THREAD

**Issue by rachelaux** [zkopru-network/wallet#25]
<img width="591" alt="No difference between standard and fast" src="https://user-images.githubusercontent.com/81319667/141700622-38b5efef-be87-4061-b797-c77aa64de724.png">

**Comment by JChanceHud** [comment]
So these definitely return different values, but there was a bug when clicking the buttons multiple times, or clicking one after the other (before the first completed loading). Going to fix this bug as part of this issue.

It takes quite a while for the fee to load for some reason.
