### ISSUE TITLE
ERC20 amount is not displayed if address starts from leading zeroes

### ISSUE THREAD

**Issue by tkmct** [zkopru-network/wallet#36]
ERC20 token amount is not displayed if tokenAddr has leading zeroes.
For example, if ERC20 token address is '0x013....', zkopru client use shortened address string for db key '0x13....' and UI does not show its amount properly.

**Comment by JChanceHud** [comment]
Hi @tkmct thanks for reporting this! This should be fixed in the latest version, could you test and let me know?

Thanks

**Comment by tkmct** [comment]
@JChanceHud It looks working fine! Thank you!!
